#ifndef __SYMBOLS_H__
#define __SYMBOLS_H__
#define END					0
#define INT					1
#define LONG				2
#define DOUBLE				3
#define SHORT				4
#define UNSIGNED			5
#define CHAR				6
#define VOID				7
#define VOLATILE			8
#define WHILE				9
#define FLOAT				10
#define IF					11
#define ELSE				12
#define RETURN				13
#define CONSTANT			14
#define STRING_LITERAL		15
#define ASSIGN				16
#define ADD					17
#define SUBSTRACT			18
#define IDENTIFIER			19
#define END_OF_INSTRUCTION	20
#define BREAK				21
#define CASE				22
#define CONST				23
#define CONTINUE			24
#define DEFAULT				25
#define DO					26
#define ENUM				27
#define EXTERN				28
#define FOR					29
#define GOTO				30
#define REGISTER			31
#define SIGNED				32
#define SIZEOF				33
#define STATIC				34
#define STRUCT				35
#define SWITCH				36
#define TYPEDEF				37
#define UNION				38
#define ELLIPSIS			39
#define RIGHT_ASSIGN		40
#define LEFT_ASSIGN			41
#define ADD_ASSIGN			42
#define SUB_ASSIGN			43
#define SUB_ASSIGN			44
#define MUL_ASSIGN			45
#define DIV_ASSIGN			46
#define MOD_ASSIGN			47
#define AND_ASSIGN			48
#define XOR_ASSIGN			49
#define OR_ASSIGN			50
#define RIGHT_OP			51
#define LEFT_OP				52
#define INC_OP				53
#define DEC_OP				53
#define PTR_OP				54
#define AND_OP				55
#define OR_OP				56
#define LE_OP				57
#define GE_OP				58
#define EQ_OP				53
#define NE_OP				53
#define COMMA				54
#define DOT					55
#define BIN_AND				56
#define NOT					57
#define BIN_COMPL			58
#define MULTIPLY			59
#define DIVIDE				60
#define MODULO				61
#define LESS				62
#define GREATER				63
#define BIN_XOR				64
#define BIN_OR				65
#define AUTO				66
#define __BOOL				67
#define __COMPLEX			68
#define __IMAGINARY			69
#endif